import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_component/Navbar/Navbar";
import Footer from "./_component/Footer/Footer";
import FirstNav from "./_component/FirstNav/FirstNav";
import { Toaster } from "@/components/ui/toast";
import MyProvider from "./_component/MyProvider/MyProvider";
import Providers from "./_component/TanstackProvider/TanstackProvider";
import FirstFooter from "./_component/FirstFooter/FirstFooter";

const Exofont = Exo({
  variable: "--font-Exo",
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${Exofont.className} antialiased`}>
      <body>
        <Providers>
          <MyProvider>
            <FirstNav />
            <Navbar />
            <div>{children}</div>
            <Toaster />
            <FirstFooter />
            <Footer />
          </MyProvider>
        </Providers>
      </body>
    </html>
  );
}
